# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: RubyCong Colombia 2015
email: organizers@rubyconf.com
description: > # this means to ignore newlines until "baseurl:"
  Ruby Conference in Medellin, Colombia
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.rubyconf.co" # the base hostname & protocol for your site
twitter_username: RubyConfCo
github_username:  RubyConfCo

# Build settings
markdown: kramdown

assets:
  root_url: '/assets'
  
sass:
    sass_dir: _sass

exclude: [
  'Gemfile',
  'Gemfile.lock',
  'README.md',
  'LICENSE',
]
